### PR TITLE
Change system_update.py and uyuni-tools/group_system_update.py for Pole

### PR DESCRIPTION
**Pull request by mbrookhuis**
- Change system_update.py and uyuni-tools/group_system_update.py for Pole Emploi
- This is a fix for Issue #12

### CODE REVIEW

**Review by juliogonzalez — CHANGES_REQUESTED** [review]
I think you need to review all .idea stuff from all places. You added them to `.gitignore`, but they are still at the PR.

**Review by rjmateus — COMMENTED** [review]
the folders "hubtools/.idea/.." and "uyuni-tools/.idea/.." still exists

**Comment by vzhestkov** [comment]
@mbrookhuis looks strange, but `hubtools/.idea/` is still in the PR. And is the change of the file permission is really required in this PR?

**Comment by mbrookhuis** [comment]
removed .idea. 
Please merge

**Comment by juliogonzalez** [comment]
> removed .idea. Please merge

Please fix the permissions as requested by Viktor, as the PR is making executable (755) a lot files that don't need to be executable (yaml, txt, md...)

My guess is that only the .py script you are changing should be executable, and not sure about a couple of other .py scripts and the file `general`.

**Review by juliogonzalez — APPROVED** [review]
LGTM, as you can see I sent the fixes for the permissions on my own, so @mbrookhuis please review in case I broke something :-D

**Review by rjmateus — APPROVED** [review]

**Pull request merged**
