### PR TITLE
Create prune_repos.sh

### PR DESCRIPTION
**Pull request by digdilem**
Unsure if this is useful, decline if not. 

A simple script that I use on a monthly basis to regain disk space from our hosted repos.  No license requirements, can be assigned whatever's convenient.

### CODE REVIEW

**Comment by SchoolGuy** [comment]
@digdilem In your last commit you deleted the whole script again. I think you might want to drop the commit 1d465f5?

**Comment by digdilem** [comment]
Hi Enno,

Thanks for the note, but this was intentional as on reviewing my code, it
referred to an external script which I couldn't include.

Sorry for the confusion

**Comment by SchoolGuy** [comment]
@digdilem So this PR is obsolete then?

**Comment by digdilem** [comment]
Yes, apologies, I thought I had closed it. Doing so now.

**Pull request closed without merging**
